---

- hosts: ubuntu
  name: Ubuntu Updates
  become: true
  roles:
    - apt

- hosts: docker
  name: Docker Updates
  roles:
    - docker

- hosts: proxmox
  name: Proxmox Updates
  roles:
    - apt
