---
- name: Wait for SSH
  ansible.builtin.wait_for:
    port: 22

- name: Pull docker-compose images
  community.docker.docker_compose_v2_pull:
    project_src: /path/to/docker/directory

- name: Restart updated docker-compose services
  community.docker.docker_compose_v2:
    project_src: /path/to/docker/directory

- name: Prune everything
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
